apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: my-app
    type: frontend
spec:
  template:
     metadata:
      labels:
        app: myapp
        type: frontend
      name: nginx
     spec:
        containers:
        - image: nginx
          name: nginx
          resources: {}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
  replicas: 3