apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name:  busybox-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - "c"
        - echo Hello MV| && sleep 3600