apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myhttpd-frontend
  name: myhttpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myhttpd-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myhttpd-frontend
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
