apiVersion: v1
kind: Pod
metadata:
  labels:
    name: ubuntu
    tier: sleeper
  name: ubuntu-sleeper-2
spec:
  containers:
  - image: ubuntu
    name: ubuntu-sleeper-2
    command:
      - "sleep"
    args:
      - "5000"