apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu
  name: ubuntu
  namespace: default
spec:
  containers:
  - command:
    - "sleep"
    - "1200"
    image: ubuntu
    imagePullPolicy: Always
    name: ubuntu
    