apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      env: dev
  replicas: 3
  template:
    metadata:
      name: nginx -2
      labels:
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx
      